[package]
name = "ray_tracing_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [build]
# target = "x86_64-pc-windows-gnu"

